name: Run CI

# Run this workflow every time a new commit is pushed to the repository
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "57 3 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13", "3.14"]

    name: Run the test suite (Python ${{ matrix.python }})

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install tox tox-uv tox-gh-actions

      - name: Run tests
        run: tox
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          FORCE_COLOR: "1"

      - name: Publish coverage report
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
